import LeftSidebar from "@/components/LeftSidebar";
import MobileBottomBar from "@/components/MobileBottomBar";
import MobileTopBar from "@/components/MobileTopBar";
import RightSidebar from "@/components/RightSidebar";
import Tweet from "@/components/Tweet";
import Head from "next/head";
import { useEffect, useState } from "react";
import { BrowserView, MobileView } from "react-device-detect";
import { useSelector } from "react-redux";

export async function getServerSideProps(context) {
  return {
    props: {
      params: context.params.id,
    },
  };
}

export default function Hashtag({ params }) {
  const [tweets, setTweets] = useState([]);
  const [loading, setLoading] = useState(true);
  const { userInfo } = useSelector((state) => state.auth);

  useEffect(() => {
    async function getTweets() {
      const token = localStorage.getItem("token");

      const data = await fetch(
        `http://localhost:3000/api/tag/tweets/${params}`,
        {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
        }
      ).then((res) => res.json());

      setTweets(data.tweets);
      setLoading(false);
    }

    getTweets();
  }, []);

  return (
    <>
      <Head>
        <title>#{params} - Tag</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BrowserView>
        <div className="bg-black flex min-h-screen text-gray-200">
          <LeftSidebar />
          <main className="flex max-w-[575px] flex-grow flex-col">
            <div
              style={{ backgroundColor: "rgba(0, 0, 0, .70)" }}
              className="py-1 pl-4 sticky top-0 flex flex-col backdrop-blur-[2px] z-[3]"
            >
              <h1 className="text-lg font-bold">#{params}</h1>
              <p className="text-sm text-secondary">{tweets.length} tweets</p>
            </div>
            {loading == true ? (
              <p>Loading...</p>
            ) : (
              tweets.map((item) => {
                return (
                  <Tweet key={item.tweet._id} tweet={item.tweet} rest={item} />
                );
              })
            )}
          </main>
          <RightSidebar />
        </div>
        {!userInfo ? (
          <div className="sticky h-[66px] text-white py-2 bottom-0 flex w-full bg-blue-500">
            <div className="w-[405px]"></div>
            <div className="flex flex-col flex-grow">
              <p className="font-bold text-lg">
                Find out what's happening right now.
              </p>
              <p>
                With twitter you can quickly find out what's happening right
                now.
              </p>
            </div>
            <div className="flex items-center gap-4 w-[540px] justify-center">
              <button
                onClick={() => {
                  setOpenLogin(true);
                  document
                    .querySelector("body")
                    .classList.toggle("overflow-hidden");
                }}
                className="bg-inherit border rounded-full h-9 w-[76px] font-bold"
              >
                Log in
              </button>
              <button
                onClick={() => {
                  setOpenRegister(true);
                  document
                    .querySelector("body")
                    .classList.toggle("overflow-hidden");
                }}
                className="bg-white text-black font-bold border rounded-full h-9 w-[132px]"
              >
                Create account
              </button>
            </div>
          </div>
        ) : (
          <></>
        )}
      </BrowserView>
      <MobileView className="bg-black min-h-screen text-white flex flex-col max-w-screen">
        <MobileTopBar
          children={
            <div className="flex flex-col px-3 pb-2">
              <h1 className="font-bold">#{params}</h1>
              <p className="text-sm text-secondary">{tweets.length} tweets</p>
            </div>
          }
        />
        <main className="flex-grow">
          {loading == true ? (
            <p>Loading...</p>
          ) : (
            tweets.map((item) => {
              return (
                <Tweet key={item.tweet._id} tweet={item.tweet} rest={item} />
              );
            })
          )}
        </main>
        <MobileBottomBar />
      </MobileView>
    </>
  );
}
