import Head from "next/head";
import Tweet from "@/components/Tweet";
import RightSidebar from "@/components/RightSidebar";
import LeftSidebar from "@/components/LeftSidebar";
import { useEffect, useState } from "react";

const backendURL = "http://localhost:3000";

export default function Bookmarks() {
  const [bookmarks, setBookmarks] = useState([]);

  useEffect(() => {
    async function getBookmarks() {
      const token = localStorage.getItem("token");

      const data = await fetch(`${backendURL}/api/bookmark`, {
        method: "GET",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })
        .then((res) => res.json())
        .catch((err) => console.log(err));

      setBookmarks(data.bookmarks);

      console.log(data);
    }

    getBookmarks();
  }, []);

  return (
    <div className="bg-black flex min-h-screen text-gray-200">
      <Head>
        <title>Bookmarks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftSidebar />
      <main className="flex flex-grow flex-col">
        <div className="py-1 pl-4 sticky top-[0.1px] flex flex-col backdrop-blur-md">
          <h1 className="text-lg font-bold">Bookmarks</h1>
          <p className="text-sm text-secondary">@username</p>
        </div>
        {bookmarks.map((item) => {
          return <Tweet key={item._id} tweet={item.tweet} rest={item} />;
        })}
      </main>
      <RightSidebar />
    </div>
  );
}
