import PostTweet from "@/components/PostTweet";
import Head from "next/head";
import Image from "next/image";
import Tweet from "@/components/Tweet";
import { useSelector } from "react-redux";
import { useEffect, useState } from "react";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import { useRouter } from "next/router";

const backendURL = "http://localhost:3000";

export default function Home() {
  const { userInfo, userToken } = useSelector((state) => state.auth);
  const [tweets, setTweets] = useState([]);
  const [pageDetails, setPageDetails] = useState({});
  const router = useRouter();

  async function fetchTweets() {
    const token = localStorage.getItem("token");

    const tweets = await fetch(
      `${backendURL}/api/tweet/?page=${pageDetails.nextPage || 1}`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    ).then((res) => res.json());

    setPageDetails(tweets.pages);
    setTweets(tweets.tweets);

    console.log(tweets.pages);
  }

  async function showMoreTweets() {
    const token = localStorage.getItem("token");

    const fetchedTweets = await fetch(
      `${backendURL}/api/tweet/?page=${pageDetails.nextPage || 1}`,
      {
        method: "GET",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    ).then((res) => res.json());

    setTweets([...tweets, ...fetchedTweets.tweets]);
    setPageDetails(fetchedTweets.pages);

    console.log(pageDetails);
  }

  function removeTweetFromArray(tweetId) {
    setTweets(tweets.filter((item) => item.tweet._id != tweetId));
  }

  function addToArray(obj) {
    setTweets([obj, ...tweets]);
  }

  useEffect(() => {
    if (!userInfo) {
      router.push("/explore");
    } else {
      fetchTweets();
    }
  }, [userInfo]);

  return (
    <div className="bg-black flex min-h-screen text-gray-200">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftSidebar />
      <main className="flex flex-grow flex-col">
        <div
          style={{ backgroundColor: "rgba(0,0,0,0.65)", zIndex: "100" }}
          className="sticky top-[0.1px] flex flex-col backdrop-blur-md border-b border-gray-700/75"
        >
          <h1 className="py-3 pl-4 text-lg font-bold">Home</h1>
          <div className="flex">
            <div className="justify-center hover:bg-zinc-800/75 flex font-bold self-start h-full flex-grow flex-basis">
              <div>
                <p className="py-[13.2px]">For you</p>
                <div className="h-[4.5px] w-[56px] rounded-full bg-sky-400"></div>
              </div>
            </div>
            <div className=" text-secondary font-bold hover:bg-zinc-800/75 flex justify-center flex-grow flex-basis">
              <p className="py-4">Following</p>
            </div>
          </div>
        </div>
        <PostTweet changeArray={addToArray} />
        {tweets.map((item) => {
          return (
            <Tweet
              key={item.tweet._id}
              tweet={item.tweet}
              rest={item}
              removeTweet={removeTweetFromArray}
            />
          );
        })}
        {pageDetails.hasNextPage == true ? (
          <p onClick={showMoreTweets}>Show more</p>
        ) : (
          <></>
        )}
      </main>
      <RightSidebar />
    </div>
  );
}
