import Head from "next/head";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { format, formatDistance } from "date-fns";

const backendURL = "http://localhost:3000";

export default function Notifications() {
  const [notifications, setNotifications] = useState([]);
  const [filteredNotifications, setFilteredNotifications] = useState([]);
  const { userInfo } = useSelector((state) => state.auth);

  useEffect(() => {
    async function getNotifcations() {
      const token = localStorage.getItem("token");

      const data = await fetch(
        `${backendURL}/api/user/${userInfo.handle}/notifications`,
        {
          method: "GET",
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      )
        .then((res) => res.json())
        .catch((err) => console.log(err));

      console.log(data);

      setNotifications(data.notifications);
      setFilteredNotifications(data.notifications);
    }

    getNotifcations();
  }, []);

  return (
    <div className="bg-black flex min-h-screen text-gray-200">
      <Head>
        <title>Notifications</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftSidebar />
      <main className="flex max-w-[575px] flex-grow flex-col">
        <div className="sticky top-[0.1px] flex flex-col backdrop-blur-md border-b border-gray-700/75">
          <h1 className="py-3 pl-4 text-lg font-bold">Notifications</h1>
          <div className="flex">
            <div className="justify-center hover:bg-zinc-800/75 flex font-bold self-start h-full flex-grow flex-basis">
              <div>
                <p className="py-[13.2px]">All</p>
                <div className="h-[4.5px] w-[23px] rounded-full bg-sky-400"></div>
              </div>
            </div>
            <div className=" text-secondary font-bold hover:bg-zinc-800/75 flex justify-center flex-grow flex-basis">
              <p className="py-4">Comments</p>
            </div>
            <div className=" text-secondary font-bold hover:bg-zinc-800/75 flex justify-center flex-grow flex-basis">
              <p className="py-4">Likes</p>
            </div>
          </div>
        </div>
        <div className="flex flex-col">
          {filteredNotifications.map((item, i) => {
            if (item.action == "comment") {
              return <div key={i} className="px-4 py-3 hover:bg-white/5"></div>;
            }
            if (item.action == "follow") {
              return (
                <div
                  key={i}
                  className="px-3 py-3 hover:bg-white/5 border-b border-stone-700/75"
                >
                  <div className="flex gap-3">
                    <img
                      src={item.user.profile_picture_url
                        .replace(`"`, "")
                        .replace(",", "")}
                      alt=""
                      className="w-12 h-12 rounded-full"
                    />
                    <div className="flex flex-col">
                      <p className="font-bold">
                        <span className="hover:underline cursor-pointer">
                          {item.user.username}
                        </span>{" "}
                        <span className="cursor-pointer text-secondary font-normal">
                          @{item.user.handle} {" · "}
                        </span>
                        <span className="text-secondary font-normal">
                          {formatDistance(new Date(item.date), new Date())}
                        </span>
                      </p>
                      <p>
                        <span className="hover:text-sky-500 cursor-pointer">
                          {item.user.username}
                        </span>{" "}
                        is now following you!
                      </p>
                    </div>
                  </div>
                </div>
              );
            }
          })}
        </div>
      </main>
      <RightSidebar />
    </div>
  );
}
