import Head from "next/head";
import Link from "next/link";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import { useEffect, useState } from "react";
import { getTagsFromBackend } from "@/lib/actions";

export default function Trends() {
  const [tags, setTags] = useState([]);

  useEffect(() => {
    async function getTags() {
      const data = await getTagsFromBackend();

      setTags(data.tags);
    }

    getTags();
  }, []);

  return (
    <div className="bg-black flex min-h-screen text-gray-200">
      <Head>
        <title>Trends</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftSidebar />
      <main className="flex max-w-[575px] flex-grow flex-col">
        <div className="sticky top-[0.1px] flex px-4 py-1 gap-6 backdrop-blur-md">
          <Link href="/" className="flex">
            <div className="flex px-2 rounded-full hover:bg-stone-900">
              <img
                src="/arrow-left.svg"
                alt="back"
                className="self-center w-6 h-6"
              />
            </div>
          </Link>
          <h1 className="py-2 text-lg font-bold">Trends</h1>
        </div>
        <div className="flex flex-col">
          {tags.map((item) => {
            return (
              <Link href={`/hashtag/${item._id.replace("#", "")}`}>
                <div key={item._id} className="px-4 py-2 hover:bg-white/5">
                  <p className="text-secondary text-sm">Trending</p>
                  <p className="font-bold">{item._id}</p>
                  <p className="text-secondary text-sm">{item.number} tweets</p>
                </div>
              </Link>
            );
          })}
        </div>
      </main>
      <RightSidebar />
    </div>
  );
}
